import {
  Ambulance,
  Apple,
  Baby,
  Bath,
  Bed,
  Bell,
  Bike,
  Book,
  BookOpen,
  Brain,
  Briefcase,
  Bus,
  Calendar,
  CalendarCheck,
  CalendarClock,
  Camera,
  Car,
  CircleHelp,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Cloud,
  Coffee,
  Compass,
  Contact,
  Dumbbell,
  ExternalLink,
  Fence,
  File,
  FileSpreadsheet,
  FileText,
  Flag,
  Flame,
  Folder,
  FolderOpen,
  Footprints,
  Gavel,
  Globe,
  GraduationCap,
  Hand,
  Handshake,
  HardDrive,
  Heart,
  HeartHandshake,
  HeartPulse,
  House,
  HouseHeart,
  HousePlus,
  IdCard,
  Info,
  Key,
  Lamp,
  Layers,
  LayoutGrid,
  LifeBuoy,
  Lightbulb,
  Link,
  ListChecks,
  Lock,
  LogIn,
  LogOut,
  Mail,
  MapPin,
  Megaphone,
  MessageCircle,
  MessageSquareHeart,
  Monitor,
  Moon,
  Mountain,
  Music,
  Newspaper,
  NotebookPen,
  Palette,
  PenLine,
  Phone,
  PhoneCall,
  Pill,
  Presentation,
  Receipt,
  Rocket,
  School,
  Search,
  Settings,
  ShieldAlert,
  ShieldCheck,
  ShoppingCart,
  Siren,
  Smartphone,
  Smile,
  Sofa,
  Soup,
  Sparkles,
  Sprout,
  Star,
  Stethoscope,
  Sun,
  Sunrise,
  Target,
  Tent,
  Thermometer,
  TreePine,
  Trees,
  TriangleAlert,
  Trophy,
  UserPlus,
  UserRound,
  Users,
  Utensils,
  Video,
  Wind,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

/**
 * מאגר האייקונים שאפשר לבחור בממשק הניהול.
 * השם נשמר בבסיס הנתונים כמחרוזת (למשל "shield-check"). כדי להוסיף אייקון:
 * מייבאים אותו מ-lucide-react ומוסיפים שורה כאן.
 */
export const ICONS = {
  "ambulance": Ambulance,
  "apple": Apple,
  "baby": Baby,
  "bath": Bath,
  "bed": Bed,
  "bell": Bell,
  "bike": Bike,
  "book": Book,
  "book-open": BookOpen,
  "brain": Brain,
  "briefcase": Briefcase,
  "bus": Bus,
  "calendar": Calendar,
  "calendar-check": CalendarCheck,
  "calendar-clock": CalendarClock,
  "camera": Camera,
  "car": Car,
  "circle-help": CircleHelp,
  "clipboard-check": ClipboardCheck,
  "clipboard-list": ClipboardList,
  "clock": Clock,
  "cloud": Cloud,
  "coffee": Coffee,
  "compass": Compass,
  "contact": Contact,
  "dumbbell": Dumbbell,
  "external-link": ExternalLink,
  "fence": Fence,
  "file": File,
  "file-spreadsheet": FileSpreadsheet,
  "file-text": FileText,
  "flag": Flag,
  "flame": Flame,
  "folder": Folder,
  "folder-open": FolderOpen,
  "footprints": Footprints,
  "gavel": Gavel,
  "globe": Globe,
  "graduation-cap": GraduationCap,
  "hand": Hand,
  "handshake": Handshake,
  "hard-drive": HardDrive,
  "heart": Heart,
  "heart-handshake": HeartHandshake,
  "heart-pulse": HeartPulse,
  "house": House,
  "house-heart": HouseHeart,
  "house-plus": HousePlus,
  "id-card": IdCard,
  "info": Info,
  "key": Key,
  "lamp": Lamp,
  "layers": Layers,
  "layout-grid": LayoutGrid,
  "life-buoy": LifeBuoy,
  "lightbulb": Lightbulb,
  "link": Link,
  "list-checks": ListChecks,
  "lock": Lock,
  "log-in": LogIn,
  "log-out": LogOut,
  "mail": Mail,
  "map-pin": MapPin,
  "megaphone": Megaphone,
  "message-circle": MessageCircle,
  "message-square-heart": MessageSquareHeart,
  "monitor": Monitor,
  "moon": Moon,
  "mountain": Mountain,
  "music": Music,
  "newspaper": Newspaper,
  "notebook-pen": NotebookPen,
  "palette": Palette,
  "pen-line": PenLine,
  "phone": Phone,
  "phone-call": PhoneCall,
  "pill": Pill,
  "presentation": Presentation,
  "receipt": Receipt,
  "rocket": Rocket,
  "school": School,
  "search": Search,
  "settings": Settings,
  "shield-alert": ShieldAlert,
  "shield-check": ShieldCheck,
  "shopping-cart": ShoppingCart,
  "siren": Siren,
  "smartphone": Smartphone,
  "smile": Smile,
  "sofa": Sofa,
  "soup": Soup,
  "sparkles": Sparkles,
  "sprout": Sprout,
  "star": Star,
  "stethoscope": Stethoscope,
  "sun": Sun,
  "sunrise": Sunrise,
  "target": Target,
  "tent": Tent,
  "thermometer": Thermometer,
  "tree-pine": TreePine,
  "trees": Trees,
  "triangle-alert": TriangleAlert,
  "trophy": Trophy,
  "user-plus": UserPlus,
  "user-round": UserRound,
  "users": Users,
  "utensils": Utensils,
  "video": Video,
  "wind": Wind,
  "wrench": Wrench,
  "zap": Zap,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;

export const ICON_NAMES = Object.keys(ICONS) as IconName[];

export function getIcon(name: string | null | undefined, fallback: IconName = "link"): LucideIcon {
  if (name && name in ICONS) return ICONS[name as IconName];
  return ICONS[fallback];
}
